name: CI -> Test
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - '.*ignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Setup Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '~1.23.0'

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install "www/" dependencies
        run: task install-www-ci

      - name: Run lint
        run: task lint

      - name: Test run dev "www/"
        run: |
          bun --cwd=./www/ run dev &
          SERVER_PID=$!
          sleep 5
          kill $SERVER_PID

      - name: Build "www/"
        run: task build-www

      - name: Build server
        run: task build-server

      - name: Test run server
        run: |
          ./dist/server &
          SERVER_PID=$!
          sleep 5
          kill $SERVER_PID
